# Generated by Django 2.2.4 on 2019-08-23 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExtTariff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ext_id', models.PositiveSmallIntegerField(db_index=True, unique=True, verbose_name='Ext tariff ID')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('size', models.CharField(max_length=64, verbose_name='Size')),
                ('websites', models.PositiveSmallIntegerField(verbose_name='Websites')),
                ('databases', models.PositiveSmallIntegerField(verbose_name='databases')),
            ],
            options={
                'verbose_name': 'External Tariff',
                'verbose_name_plural': 'External Tariffs',
            },
        ),
        migrations.CreateModel(
            name='ExtUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ext_id', models.PositiveSmallIntegerField(db_index=True, unique=True, verbose_name='Ext user ID')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('username', models.CharField(max_length=64, verbose_name='Username')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'External User',
                'verbose_name_plural': 'External Users',
            },
        ),
        migrations.CreateModel(
            name='ClientInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success', models.CharField(choices=[(False, 'Not success'), (True, 'Success')], default=False, max_length=8, verbose_name='Success')),
                ('status', models.CharField(choices=[('TRIAL', 'Trial'), ('MEDIUM', 'Medium'), ('NORMAL', 'Large')], default='TRIAL', max_length=8, verbose_name='Status')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_info.ExtUser')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_info.ExtTariff')),
            ],
            options={
                'verbose_name': 'Client Info',
                'verbose_name_plural': 'Clients Info',
            },
        ),
    ]
