openapi: 3.0.2
info:
  title: ''
  version: TODO
paths:
  /api/v1/auth/users/:
    get:
      operationId: ListUsers
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                required:
                - username
                properties:
                  username:
                    type: string
                    maxLength: 255
                  id:
                    type: integer
                    readOnly: true
                  email:
                    type: string
                    readOnly: true
    post:
      operationId: createUser
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              required:
              - username
              - email
              - password
              properties:
                username:
                  type: string
                  maxLength: 255
                email:
                  type: string
                  maxLength: 255
                password:
                  type: string
                  writeOnly: true
      responses:
        '200':
          content:
            application/json:
              schema:
                required:
                - username
                - email
                properties:
                  username:
                    type: string
                    maxLength: 255
                  email:
                    type: string
                    maxLength: 255
                  id:
                    type: integer
                    readOnly: true
  /api/v1/auth/users/me/:
    get:
      operationId: meUser
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                required:
                - username
                properties:
                  username:
                    type: string
                    maxLength: 255
                  id:
                    type: integer
                    readOnly: true
                  email:
                    type: string
                    readOnly: true
    put:
      operationId: meUser
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              required:
              - username
              properties:
                username:
                  type: string
                  maxLength: 255
      responses:
        '200':
          content:
            application/json:
              schema:
                required:
                - username
                properties:
                  username:
                    type: string
                    maxLength: 255
                  id:
                    type: integer
                    readOnly: true
                  email:
                    type: string
                    readOnly: true
    patch:
      operationId: meUser
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              properties:
                username:
                  type: string
                  maxLength: 255
      responses:
        '200':
          content:
            application/json:
              schema:
                required:
                - username
                properties:
                  username:
                    type: string
                    maxLength: 255
                  id:
                    type: integer
                    readOnly: true
                  email:
                    type: string
                    readOnly: true
    delete:
      operationId: meUser
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                required:
                - username
                properties:
                  username:
                    type: string
                    maxLength: 255
                  id:
                    type: integer
                    readOnly: true
                  email:
                    type: string
                    readOnly: true
  /api/v1/auth/users/{id}/:
    get:
      operationId: retrieveUser
      parameters:
      - name: id
        in: path
        required: true
        description: "A unique integer value identifying this \u041F\u043E\u043B\u044C\
          \u0437\u043E\u0432\u0430\u0442\u0435\u043B\u044C."
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                required:
                - username
                properties:
                  username:
                    type: string
                    maxLength: 255
                  id:
                    type: integer
                    readOnly: true
                  email:
                    type: string
                    readOnly: true
    put:
      operationId: updateUser
      parameters:
      - name: id
        in: path
        required: true
        description: "A unique integer value identifying this \u041F\u043E\u043B\u044C\
          \u0437\u043E\u0432\u0430\u0442\u0435\u043B\u044C."
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              required:
              - username
              properties:
                username:
                  type: string
                  maxLength: 255
      responses:
        '200':
          content:
            application/json:
              schema:
                required:
                - username
                properties:
                  username:
                    type: string
                    maxLength: 255
                  id:
                    type: integer
                    readOnly: true
                  email:
                    type: string
                    readOnly: true
    patch:
      operationId: partial_updateUser
      parameters:
      - name: id
        in: path
        required: true
        description: "A unique integer value identifying this \u041F\u043E\u043B\u044C\
          \u0437\u043E\u0432\u0430\u0442\u0435\u043B\u044C."
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              properties:
                username:
                  type: string
                  maxLength: 255
      responses:
        '200':
          content:
            application/json:
              schema:
                required:
                - username
                properties:
                  username:
                    type: string
                    maxLength: 255
                  id:
                    type: integer
                    readOnly: true
                  email:
                    type: string
                    readOnly: true
    delete:
      operationId: destroyUser
      parameters:
      - name: id
        in: path
        required: true
        description: "A unique integer value identifying this \u041F\u043E\u043B\u044C\
          \u0437\u043E\u0432\u0430\u0442\u0435\u043B\u044C."
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                required:
                - current_password
                properties:
                  current_password:
                    type: string
  /api/v1/forms/all/:
    get:
      operationId: ListForms
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                required:
                - name
                - user
                properties:
                  id:
                    type: integer
                    readOnly: true
                  name:
                    type: string
                    maxLength: 128
                  user:
                    type: integer
  /api/v1/forms/detail/{id}/:
    get:
      operationId: RetrieveForm
      parameters:
      - name: id
        in: path
        required: true
        description: "A unique integer value identifying this \u0424\u043E\u0440\u043C\
          \u0430."
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                required:
                - name
                properties:
                  id:
                    type: integer
                    readOnly: true
                  name:
                    type: string
                    maxLength: 128
    put:
      operationId: UpdateForm
      parameters:
      - name: id
        in: path
        required: true
        description: "A unique integer value identifying this \u0424\u043E\u0440\u043C\
          \u0430."
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              required:
              - name
              properties:
                name:
                  type: string
                  maxLength: 128
      responses:
        '200':
          content:
            application/json:
              schema:
                required:
                - name
                properties:
                  id:
                    type: integer
                    readOnly: true
                  name:
                    type: string
                    maxLength: 128
    patch:
      operationId: PartialUpdateForm
      parameters:
      - name: id
        in: path
        required: true
        description: "A unique integer value identifying this \u0424\u043E\u0440\u043C\
          \u0430."
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              properties:
                name:
                  type: string
                  maxLength: 128
      responses:
        '200':
          content:
            application/json:
              schema:
                required:
                - name
                properties:
                  id:
                    type: integer
                    readOnly: true
                  name:
                    type: string
                    maxLength: 128
    delete:
      operationId: DestroyForm
      parameters:
      - name: id
        in: path
        required: true
        description: "A unique integer value identifying this \u0424\u043E\u0440\u043C\
          \u0430."
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                required:
                - name
                properties:
                  id:
                    type: integer
                    readOnly: true
                  name:
                    type: string
                    maxLength: 128
  /api/v1/auth/users/activation/:
    post:
      operationId: activationUser
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              required:
              - uid
              - token
              properties:
                uid:
                  type: string
                token:
                  type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                required:
                - uid
                - token
                properties:
                  uid:
                    type: string
                  token:
                    type: string
  /api/v1/auth/users/resend_activation/:
    post:
      operationId: resend_activationUser
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              required:
              - email
              properties:
                email:
                  type: string
                  format: email
      responses:
        '200':
          content:
            application/json:
              schema:
                required:
                - email
                properties:
                  email:
                    type: string
                    format: email
  /api/v1/auth/users/reset_password/:
    post:
      operationId: reset_passwordUser
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              required:
              - email
              properties:
                email:
                  type: string
                  format: email
      responses:
        '200':
          content:
            application/json:
              schema:
                required:
                - email
                properties:
                  email:
                    type: string
                    format: email
  /api/v1/auth/users/reset_password_confirm/:
    post:
      operationId: reset_password_confirmUser
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              required:
              - uid
              - token
              - new_password
              properties:
                uid:
                  type: string
                token:
                  type: string
                new_password:
                  type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                required:
                - uid
                - token
                - new_password
                properties:
                  uid:
                    type: string
                  token:
                    type: string
                  new_password:
                    type: string
  /api/v1/auth/users/reset_email/:
    post:
      operationId: reset_usernameUser
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              required:
              - email
              properties:
                email:
                  type: string
                  format: email
      responses:
        '200':
          content:
            application/json:
              schema:
                required:
                - email
                properties:
                  email:
                    type: string
                    format: email
  /api/v1/auth/users/reset_email_confirm/:
    post:
      operationId: reset_username_confirmUser
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              required:
              - new_email
              properties:
                new_email:
                  type: string
                  maxLength: 255
      responses:
        '200':
          content:
            application/json:
              schema:
                required:
                - new_email
                properties:
                  new_email:
                    type: string
                    maxLength: 255
  /api/v1/auth/users/set_password/:
    post:
      operationId: set_passwordUser
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              required:
              - new_password
              - current_password
              properties:
                new_password:
                  type: string
                current_password:
                  type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                required:
                - new_password
                - current_password
                properties:
                  new_password:
                    type: string
                  current_password:
                    type: string
  /api/v1/auth/users/set_email/:
    post:
      operationId: set_usernameUser
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              required:
              - new_email
              properties:
                new_email:
                  type: string
                  maxLength: 255
      responses:
        '200':
          content:
            application/json:
              schema:
                required:
                - new_email
                properties:
                  new_email:
                    type: string
                    maxLength: 255
  /api/v1/auth_token/token/login/:
    post:
      operationId: CreateTokenCreate
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              required: []
              properties:
                password:
                  type: string
                email:
                  type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                required: []
                properties:
                  password:
                    type: string
                  email:
                    type: string
  /api/v1/auth_token/token/logout/:
    post:
      operationId: CreateTokenDestroy
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema: {}
  /api/v1/forms/create/:
    post:
      operationId: CreateForm
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              required:
              - name
              properties:
                name:
                  type: string
                  maxLength: 128
      responses:
        '200':
          content:
            application/json:
              schema:
                required:
                - name
                properties:
                  id:
                    type: integer
                    readOnly: true
                  name:
                    type: string
                    maxLength: 128
  /api/v1/client_info/:
    post:
      operationId: Createget_client_info
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema: {}
